---
title: Holy simple features and leaflet!
author: Eric C. Anderson
date: '2017-07-26'
slug: holy-simple-features-and-leaflet
categories: []
tags: []
---

My mind has just been blown. I have been drinking Hadley's tidyverse
Kool-aid for a couple of years now.  I'm just wrapping up a seminar
in UCSC's Ecology and Evolutionary Biology Department on reproducible
research.  One thing that ecologists always want to do is make nice maps
of their study sites.  Further, spatial data is now a lot easier to come
by and can provide a lot of meaninful inference.

I started off with a session about [making simple maps in R](https://eriqande.github.io/rep-res-eeb-2017/map-making-in-R.html).
Then, last week I gave a lecture on using R to plot spatial data using
[R's traditional sp and raster packages](https://eriqande.github.io/rep-res-eeb-2017/plotting-spatial-data-with-ggplot.html).

This week we were planning to have some student presentations, but I started
reading about the new R package `sf` that implements [Simple Features](https://en.wikipedia.org/wiki/Simple_Features)
for R. Simple Features is a standard that makes spatial data more amenable to storage
and manipulation in relational data bases.  As such, it makes it perfect for handling 
spatial data in tidy data frames.  The `sf` package is written by tidyverse aficionados
who make great use of list columns to bring a lovely package to the R world.

I think the students were quite happy to postpone their presentations, and I really
wanted to show them the simple features stuff.
The lecture notes I gave about simple features are available [here](https://eriqande.github.io/rep-res-eeb-2017/a-tidy-approach-to-spatial-data-simple-features.html).
In it I also explore the quick and easy creation of interactive maps using 
the leaflet-powered [mapview](https://r-spatial.github.io/mapview/) package.

